version: '3.8'

services:
  postgres:
    image: debezium/postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  starrocks-fe:
    image: starrocks/fe-ubuntu:3.2-latest
    ports:
      - "8030:8030"
      - "9030:9030"
    volumes:
      - starrocks-fe-data:/opt/starrocks/fe/meta
    command: /opt/starrocks/fe/bin/start_fe.sh && tail -f /opt/starrocks/fe/log/fe.out

  starrocks-be:
    image: starrocks/be-ubuntu:3.2-latest
    ports:
      - "8040:8040"
    volumes:
      - starrocks-be-data:/opt/starrocks/be/storage
    command: /opt/starrocks/be/bin/start_be.sh && tail -f /opt/starrocks/be/log/be.out

  jobmanager:
    image: flink:1.17
    ports:
      - "8081:8081"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    command: jobmanager

  taskmanager:
    image: flink:1.17
    depends_on:
      - jobmanager
    command: taskmanager

volumes:
  starrocks-fe-data:
  starrocks-be-data:
